# Generated by Django 4.1 on 2022-09-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_alter_blogcomment_post'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
