# Generated by Django 4.1 on 2022-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
