# Generated by Django 4.1 on 2022-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='static/image')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
