# Generated by Django 4.1 on 2022-09-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user2_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2',
            name='dob',
        ),
    ]
