# Generated by Django 4.1 on 2022-09-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_user2_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user2',
        ),
    ]
