# Generated by Django 4.1 on 2022-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='static.img')),
            ],
        ),
    ]
